CAPTION_TABLE = 'table'
CAPTION_TABLE_PREFIX = '表'
CAPTION_IMAGE = 'image'
CAPTION_IMAGE_PREFIX = '图'


TOC_STYLE_HEADING_1 = 'TOCHeading1'
TOC_STYLE_HEADING_2 = 'TOCHeading2'
TOC_STYLE_HEADING_3 = 'TOCHeading3'
TOC_STYLE_HEADING_4 = 'TOCHeading4'


STYLE_NORMAL = 'Normal'
STYLE_COMMENT = 'Comment'
STYLE_INDENT_0 = 'Indent0'
STYLE_INDENT_1 = 'Indent1'
STYLE_INDENT_2 = 'Indent2'
STYLE_BODY_TEXT = 'BodyText'
STYLE_ITALIC = 'Italic'
STYLE_HEADING_1 = 'Heading1'
STYLE_HEADING_2 = 'Heading2'
STYLE_HEADING_3 = 'Heading3'
STYLE_HEADING_4 = 'Heading4'
STYLE_TITLE = 'Title'
STYLE_BULLET = 'Bullet'
STYLE_DEFINITION = 'Definition'
STYLE_CODE = 'Code'
STYLE_LINK = 'Link'
STYLE_FUNCTION_HEADER = 'FunctionHeader'
STYLE_DOC_STRING = 'DocString'
STYLE_DOC_STRING_INDENT = 'DocStringIndent'
STYLE_URL = 'URL'
STYLE_CENTRED = 'Centred'
STYLE_CAPTION = 'Caption'
STYLE_H1 = 'h1'
STYLE_H2 = 'h2'
STYLE_H3 = 'h3'
STYLE_H4 = 'h4'
STYLE_T = 't'
STYLE_BU = 'bu'
STYLE_DF = 'df'
STYLE_U = 'u'

ALL_STYLES = (
    STYLE_NORMAL,
    STYLE_COMMENT,
    STYLE_INDENT_0,
    STYLE_INDENT_1,
    STYLE_INDENT_2,
    STYLE_BODY_TEXT,
    STYLE_ITALIC,
    STYLE_HEADING_1,
    STYLE_HEADING_2,
    STYLE_HEADING_3,
    STYLE_HEADING_4,
    STYLE_TITLE,
    STYLE_BULLET,
    STYLE_DEFINITION,
    STYLE_CODE,
    STYLE_LINK,
    STYLE_FUNCTION_HEADER,
    STYLE_DOC_STRING,
    STYLE_DOC_STRING_INDENT,
    STYLE_URL,
    STYLE_CENTRED,
    STYLE_CAPTION,
    STYLE_H1,
    STYLE_H2,
    STYLE_H3,
    STYLE_H4,
    STYLE_T,
    STYLE_BU,
    STYLE_DF,
    STYLE_U,
)

TEMPLATE_COVER = 'Cover'
TEMPLATE_TOC = 'TOC'
TEMPLATE_NORMAL = 'Normal'
TEMPLATE_TWO_COLUMN = 'TwoColumn'

EXAMPLE_FUNCTION_X_INCHES = 5.5
EXAMPLE_FUNCTION_Y_INCHES = 3
