"An Area Chart"
# Autogenerated by ReportLab guiedit do not edit
from rlextra.graphics.quickchart import QuickChartDrawing, QuickChart
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin


class QuickAreaChart01(_DrawingEditorMixin, QuickChartDrawing):
    def __init__(self, width=400, height=200, *args, **kw):
        titleFontName = kw.pop('titleFontName', 'Helvetica')

        QuickChartDrawing.__init__(self, width, height, *args, **kw)
        self.qc.chartType = 'area'
        self.qc.titleText = '面积图'  # 'Quick Area Chart'
        self.qc.titleFontName = titleFontName
        self.qc.categoryNames = '2002', '2003', '2004', '2005'
        self.qc.seriesNames = 'England', 'France'


class Drawing3DBarChart(_DrawingEditorMixin, Drawing):
    """
    3d Bar Chart - with 2 series & gridlines
    """

    def __init__(self, width=400, height=200, *args, **kw):

        titleFontName = kw.pop('titleFontName', 'Helvetica')

        Drawing.__init__(self, width, height, *args, **kw)
        self._add(self, QuickChart(), name='chart', validate=None, desc=None)
        self.chart.height = 200
        self.chart.seriesNames = 'profit', 'sales'
        self.chart.yAxisFontSize = 9
        self.chart.yAxisGridLines = 1
        self.chart.yAxisLabelTextFormat = None
        self.chart.chartSeparation = 1
        self.chart.titleText = '3D 条形图'  # '3d Bar Chart'
        self.chart.titleFontName = titleFontName
        self.chart.yAxisVisible = 1
        self.chart.yTitleFontSize = 9
        self.chart.yAxisLabelTextScale = None
        self.chart.yTitleText = None
        self.chart.pointerLabelMode = 'LeftRight'
        self.chart.chartType = 'bar3d'
        self.chart.categoryNames = ('2009', '2010', '2011', '2012')
        self.chart.xTitleText = 'Euro (thousands)'
        self.chart.xAxisGridLines = 1
        self.chart.x = 0
        self.chart.showBoundaries = 0
        self.chart.seriesRelation = 1


class QuickBarChart01(_DrawingEditorMixin, QuickChartDrawing):
    def __init__(self, width=400, height=200, *args, **kw):
        titleFontName = kw.pop('titleFontName', 'Helvetica')

        QuickChartDrawing.__init__(self, width, height, *args, **kw)
        self.qc.categoryNames = ('2000', '2001', '2002', '2003')
        self.qc.titleText = '柱状图'
        self.qc.seriesNames = 'US', 'UK'
        self.qc.titleFontName = titleFontName
